FROM openjdk:8
ADD C:\Users\vrair\.m2\repository\com\raauf\green_numbers\0.0.1-SNAPSHOT\green_numbers-0.0.1-SNAPSHOT.jar green_numbers_server.jar
ENTRYPOINT ["java", "-jar", "green_numbers_server.jar"]
